### ISSUE TITLE
The way pi estimation accuracy is graphed is buggy 

### ISSUE THREAD

**Issue by shak360** [meyer-lab/tHMM#420]
![image](https://user-images.githubusercontent.com/20716101/85956973-467e1380-b93e-11ea-99fd-37c3a29f92c9.png)

A pattern like this indicates that something is wrong with the way the norm that is being plotted is calculated.

**Comment by shak360** [comment]
```
    # Rearrange the values in the pi vector
    temp_pi = np.copy(tHMMobj.estimate.pi)
    for val_idx in range(tHMMobj.num_states):
        temp_pi[val_idx] = tHMMobj.estimate.pi[switcher_map[val_idx]]

    results_dict["switched_pi_vector"] = temp_pi
    results_dict["pi_vector_norm"] = np.linalg.norm(temp_pi - tHMMobj.X[0].pi)
```

See the following lines here: https://github.com/meyer-lab/lineage-growth/blob/54de1cd89bd922afd022860184722abfb549244c/lineage/Analyze.py#L134 

I have a feeling that the subtraction done in the last line, in the argument of the norm function, is wrong in some way, and would be a good place to start debugging.

**Comment by jclagarde** [comment]
the discrepancy between the temp_pi and pi object happens in this for loop. I suspect it might be due to the switcher map function. I've been going through it and haven't found any errors but I'm also a bit confused by it

<img width="666" alt="Screen Shot 2020-07-06 at 11 21 02 PM" src="https://user-images.githubusercontent.com/54101546/86726424-66b56e80-bfdf-11ea-8c68-934e841847fb.png">
<img width="236" alt="Screen Shot 2020-07-06 at 11 20 51 PM" src="https://user-images.githubusercontent.com/54101546/86726432-6917c880-bfdf-11ea-9231-514a855bdff9.png">
