### ISSUE TITLE
More functionality to lineage plotting

### ISSUE THREAD

**Issue by shak360** [meyer-lab/tHMM#446]
- Lineage tree plotting needs an axis that denotes time.
- The output of the plot is currently an SVG, but should ideally be an matplotlib figure or an axes object.
- Currently, only one lineage can be plotted at a time; ideally, we should have the ability to plot a list of lineages (a population)

**Comment by Farnazmdi** [comment]
I think working with `Phylo` has limitations. 
For the axis, I insert a cartoon because it looks like the axis is not really editable. 
For those that needed more than 1 lineage, I plotted them separately and placed them together.
@shak360 If you think this matters we may need to look into that more deeply, but I couldn't plot more than 1 lineage with one `Phylo.draw()` call. My opinion is that they are mostly for the purpose of the paper and it should be fine to have them as they are.

**Comment by shak360** [comment]
Yea I agree, the goal of this issue was to design something that would replace whatever tool the other lab that provided us the data used to generate lineage diagrams. But unless we need a different kind of figure for the paper, then I agree that it isn't necessary.

**Comment by Farnazmdi** [comment]
@shak360 is it alright if I close this issue?

**Comment by shak360** [comment]
Yep, if its not immediately relevant to the paper (which it doesn't seem like) then feel free to close it.
