### ISSUE TITLE
We should show a baseline on the Wasserstein plots

### ISSUE THREAD

**Issue by aarmey** [meyer-lab/tHMM#662]
This could be the distance using just a one-state model. It should only need to be calculated once rather than for each point.

**Comment by Farnazmdi** [comment]
@aarmey How about we calculate kmeans as the baseline? Because if we want to fit a 1-state model to the existing population (that has been created with 2 states), then we won't know the true 1-state parameters to find the wass. distance between the model and the estimate. On the other hand, if we create a new 1-state population and fit a 1-state model to it, it won't have anything in common with the two-state population we originally had on the plot, so I guess won't serve as a good baseline.

**Comment by aarmey** [comment]
K-means won't work with censorship. I see your point about not knowing which state to compare to. Maybe we can just add a description of what a "good" Wasserstein distance is in the text...
